name: Go test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    - run: make test
